# AssetMapper desativado - usando assets est√°ticos do template Dasher
# framework:
#     asset_mapper:
#         # The paths to make available to the asset mapper.
#         paths:
#             - assets/
#         missing_import_mode: strict

# when@prod:
#     framework:
#         asset_mapper:
#             missing_import_mode: warn
